// Tabla canónica de mutaciones (sibling de mutation-contract.ts; hard 300 LOC).
// Siblings: .supervisor | .payment-intents | .integrations | .settings | .catalogo | .caja
// Todos se spread al final.
import type { MutationContractEntry } from "./mutation-contract-types";
import { SUPERVISOR_INTERNAL_MUTATION_CONTRACT } from "./mutation-contract-entries.supervisor";
import { PAYMENT_INTENT_MUTATION_CONTRACT } from "./mutation-contract-entries.payment-intents";
import { INTEGRATIONS_MUTATION_CONTRACT } from "./mutation-contract-entries.integrations";
import { SETTINGS_MUTATION_CONTRACT } from "./mutation-contract-entries.settings";
import { CATALOGO_MUTATION_CONTRACT } from "./mutation-contract-entries.catalogo";
import { CAJA_MUTATION_CONTRACT } from "./mutation-contract-entries.caja";
export const SERVER_MUTATION_CONTRACT = {
  "sale.create": {
    actionType: "sale.create",
    routeScope: "sales/create",
    resourceType: "sale",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["sale-item.create", "inventory.decrement", "stock-movement.create", "cash-movement.create", "invoice.create"],
  },
  "stock-load.create": {
    actionType: "stock-load.create",
    routeScope: "stock-loads",
    resourceType: "stock-load",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["product.resolve-or-create", "inventory.increment", "stock-movement.create", "cash-movement.create", "supplier.resolve-or-create", "purchase-request.create"],
  },
  "cash-movement.create": {
    actionType: "cash-movement.create",
    routeScope: "cash-movements",
    resourceType: "cash_movement",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
  },
  "product.create": {
    actionType: "product.create",
    routeScope: "products",
    resourceType: "product",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["inventory.create", "stock-movement.create"],
  },
  "product.update": {
    actionType: "product.update",
    routeScope: "products",
    resourceType: "product",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["inventory.adjust", "stock-movement.create"],
  },
  "product.delete": {
    actionType: "product.delete",
    routeScope: "products",
    resourceType: "product",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["inventory.delete"],
  },
  "product.bulk-price-update": {
    actionType: "product.bulk-price-update",
    routeScope: "products/bulk-price-update",
    resourceType: "product",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
  },
  "product.multi-price-update": {
    actionType: "product.multi-price-update",
    routeScope: "products/multi-price-update",
    resourceType: "product",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
  },
  "product.resolve-or-create": {
    actionType: "product.resolve-or-create",
    routeScope: "products/resolve-or-create",
    resourceType: "product",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["inventory.create"],
  },
  "customer.create": {
    actionType: "customer.create",
    routeScope: "customers",
    resourceType: "customer",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
  },
  "customer.update": {
    actionType: "customer.update",
    routeScope: "customers",
    resourceType: "customer",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
  },
  "customer.delete": {
    actionType: "customer.delete",
    routeScope: "customers",
    resourceType: "customer",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["invoice.customer-detach", "sale.customer-detach"],
  },
  "supplier.create": {
    actionType: "supplier.create",
    routeScope: "suppliers",
    resourceType: "supplier",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
  },
  "supplier.update": {
    actionType: "supplier.update",
    routeScope: "suppliers",
    resourceType: "supplier",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
  },
  "supplier.delete": {
    actionType: "supplier.delete",
    routeScope: "suppliers",
    resourceType: "supplier",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["purchase-request.supplier-detach"],
  },
  "invoice.update-status": {
    actionType: "invoice.update-status",
    routeScope: "invoices/status",
    resourceType: "invoice",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
  },
  "invoice.send-whatsapp": {
    actionType: "invoice.send-whatsapp",
    routeScope: "invoices/send-whatsapp",
    resourceType: "invoice",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["whatsapp.send"],
  },
  "business.update": {
    actionType: "business.update",
    routeScope: "business",
    resourceType: "business",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
  },
  "undo.execute": {
    actionType: "undo.execute",
    routeScope: "undo",
    resourceType: "undo",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["undo.sale", "undo.customer", "undo.stock", "undo.product"],
  },
  "purchase-request.create": {
    actionType: "purchase-request.create",
    routeScope: "purchase-requests",
    resourceType: "purchase-request",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["supplier.resolve-or-create", "mock-purchase-request.create"],
  },
  "purchase-request.send-whatsapp": {
    actionType: "purchase-request.send-whatsapp",
    routeScope: "purchase-requests/send-whatsapp",
    resourceType: "purchase_request",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["whatsapp.send"],
  },
  "import.create": {
    actionType: "import.create",
    routeScope: "import",
    resourceType: "import",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "derived",
    compositeChildren: ["product.upsert", "customer.upsert", "supplier.upsert", "inventory.adjust"],
  },
  "budget.create": {
    actionType: "budget.create",
    routeScope: "budgets",
    resourceType: "budget",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["budget-item.create"],
  },
  "budget.delete": {
    actionType: "budget.delete",
    routeScope: "budgets",
    resourceType: "budget",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
  },
  "budget.send-whatsapp": {
    actionType: "budget.send-whatsapp",
    routeScope: "budgets/send-whatsapp",
    resourceType: "budget",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["whatsapp.send"],
  },
  "onboarding.complete": {
    actionType: "onboarding.complete",
    routeScope: "onboarding",
    resourceType: "business",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["business.create", "product.create", "customer.create", "supplier.create"],
  },
  "onboarding.orchestrate": {
    actionType: "onboarding.orchestrate",
    routeScope: "onboarding-orchestrator",
    resourceType: "business",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
    compositeChildren: ["business.create", "product.create", "customer.create"],
  },
  "onboarding.chat": {
    actionType: "onboarding.chat",
    routeScope: "onboarding-chat",
    resourceType: "business",
    requiresTrace: true,
    requiresIdempotency: false,
    idempotencyStrategy: "header",
    compositeChildren: ["business.create", "product.create"],
  },
  "push-notifications.subscribe": {
    actionType: "push-notifications.subscribe",
    routeScope: "push-notifications/subscribe",
    resourceType: "push_subscription",
    requiresTrace: true,
    requiresIdempotency: true, idempotencyStrategy: "header",
  },
  "employee.create": {
    actionType: "employee.create",
    routeScope: "employees.create",
    resourceType: "Employee",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
  },
  "employee.revoke": {
    actionType: "employee.revoke",
    routeScope: "employees.delete",
    resourceType: "Employee",
    requiresTrace: true,
    requiresIdempotency: true,
    idempotencyStrategy: "header",
  },
  "employee.login": {
    actionType: "employee.login",
    routeScope: "employees.login",
    resourceType: "Employee",
    requiresTrace: false,
    requiresIdempotency: false,
    idempotencyStrategy: "header",
  },
  "employee.logout": {
    actionType: "employee.logout",
    routeScope: "employees.logout",
    resourceType: "Employee",
    requiresTrace: false,
    requiresIdempotency: false,
    idempotencyStrategy: "header",
  },
  ...CATALOGO_MUTATION_CONTRACT,
  ...INTEGRATIONS_MUTATION_CONTRACT,
  ...PAYMENT_INTENT_MUTATION_CONTRACT,
  ...SUPERVISOR_INTERNAL_MUTATION_CONTRACT,
  ...SETTINGS_MUTATION_CONTRACT,
  ...CAJA_MUTATION_CONTRACT,
} as const satisfies Record<string, MutationContractEntry>;
