// PedidosYa Courier API v3 — thin HTTP client helpers.
//
// API source (OpenAPI spec HTTP 200 verified 2026-06-04):
//   https://developers.pedidosya.com/courier-api/v3.json  (Redoc spec behind
//   https://developers.pedidosya.com/courier-api/v3)
//   servers[0].url = https://courier-api.pedidosya.com
//
// Auth (spec info.description): "All endpoints require an authorization header
// with a token value. The content of the header should look like the following:
// 'Authorization: token'". The token is pre-generated by the partner — there is
// NO token-exchange endpoint. We send it verbatim as the Authorization header.
//
// Real endpoints (from the OpenAPI paths):
//   POST /v3/shippings/estimates           → quote   (deliveryOffers[].pricing.total)
//   POST /v3/shippings                      → create  (shippingId, confirmationCode, status)
//   GET  /v3/shippings/{shippingId}         → status  (status enum)
//   GET  /v3/shippings/{shippingId}/tracking → live position (lat/lon/eta)
//
// BYOA: the per-business token is passed in by the caller (loaded from
// BusinessChannelCredential). The PEDIDOSYA_API_TOKEN env var is a global
// fallback only. All calls are tenant-scoped through the supplied token.
//
// All network calls are isolated here so pedidosya-adapter.ts stays thin.

import type {
  PedidosYaEstimateResponse,
  PedidosYaShippingResponse,
  PedidosYaTrackingResponse,
  PedidosYaQuoteOption,
  PedidosYaQuoteResult,
  PedidosYaCreateResult,
  PedidosYaTrackResult,
} from "./pedidosya-types";

const PYA_BASE_URL = process.env.PEDIDOSYA_API_URL ?? "https://courier-api.pedidosya.com";

/** Global fallback token. Per-business BYOA token is preferred (passed by caller). */
export function envPedidosYaToken(): string {
  return (process.env.PEDIDOSYA_API_TOKEN ?? "").trim();
}

// ── Param coercion helpers ──────────────────────────────────────────────────

function str(params: Record<string, unknown>, key: string): string {
  const v = params[key];
  return typeof v === "string" && v.trim() ? v.trim() : "";
}

function num(params: Record<string, unknown>, key: string, fallback: number): number {
  const v = params[key];
  return typeof v === "number" && isFinite(v) ? v : fallback;
}

/** Shared header set — Authorization carries the token verbatim (no Bearer). */
function authHeaders(token: string): Record<string, string> {
  return { "Content-Type": "application/json", Authorization: token };
}

/** Build the two-waypoint payload shared by estimate and create.
 *  PICK_UP = origin (business), DROP_OFF = destination (customer). */
function buildShippingPayload(
  params: Record<string, unknown>,
  customer: Record<string, unknown>,
  referenceId: string,
): Record<string, unknown> {
  const weightKg = Math.max(0.1, num(params, "weightGrams", 500) / 1000);
  const declaredValue = num(params, "declaredValue", 0);
  return {
    referenceId,
    isTest: (process.env.PEDIDOSYA_API_ENV ?? "").toLowerCase() === "sandbox",
    items: [
      {
        type: "STANDARD",
        value: declaredValue,
        description: str(params, "itemDescription") || "Pedido",
        quantity: 1,
        volume: num(params, "volumeLiters", 1),
        weight: weightKg,
      },
    ],
    waypoints: [
      {
        type: "PICK_UP",
        addressStreet: str(params, "originAddress") || str(params, "originPostalCode") || "Punto de pickup",
        city: str(params, "originCity") || "Buenos Aires",
        name: str(params, "originName") || "Comercio",
        phone: str(params, "originPhone") || "0",
      },
      {
        type: "DROP_OFF",
        addressStreet:
          str(customer, "address") ||
          str(params, "destinationAddress") ||
          str(params, "destinationPostalCode") ||
          "Sin dirección",
        addressAdditional: str(customer, "addressNumber"),
        city: str(customer, "city") || str(params, "destinationCity") || "Buenos Aires",
        name: str(customer, "name") || "Cliente",
        phone: str(customer, "phone") || "0",
      },
    ],
  };
}

// ── Quote (estimate) ────────────────────────────────────────────────────────

/** Call POST /v3/shippings/estimates and return the shaped quote result. */
export async function fetchPedidosYaEstimate(
  token: string,
  params: Record<string, unknown>,
  originPostalCode: string,
  destinationPostalCode: string,
): Promise<PedidosYaQuoteResult> {
  const payload = buildShippingPayload(params, {}, `est-${Date.now()}`);
  const res = await fetch(`${PYA_BASE_URL}/v3/shippings/estimates`, {
    method: "POST",
    headers: authHeaders(token),
    body: JSON.stringify(payload),
  });
  if (!res.ok) throw new Error(`PedidosYa estimate failed: ${res.status} ${res.statusText}`);

  const data = (await res.json()) as PedidosYaEstimateResponse;
  const options: PedidosYaQuoteOption[] = (data.deliveryOffers ?? []).map((o) => ({
    service: o.deliveryMode ?? "EXPRESS",
    serviceLabel: o.deliveryMode === "SCHEDULED" ? "Envío programado" : "Envío express",
    priceARS: o.pricing?.total ?? 0,
    estimatedDays: 0,
    estimatedMinutes:
      typeof o.estimatedDrivingTime === "number" ? Math.round(o.estimatedDrivingTime / 60) : undefined,
  }));
  return { originPostalCode, destinationPostalCode, provider: "pedidosya", options };
}

// ── Create shipping ─────────────────────────────────────────────────────────

/** Call POST /v3/shippings and return the shaped create result. */
export async function fetchPedidosYaCreate(
  token: string,
  params: Record<string, unknown>,
  customer: Record<string, unknown>,
  saleId: string,
): Promise<PedidosYaCreateResult> {
  const payload = buildShippingPayload(params, customer, saleId);
  const res = await fetch(`${PYA_BASE_URL}/v3/shippings`, {
    method: "POST",
    headers: authHeaders(token),
    body: JSON.stringify(payload),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => res.statusText);
    throw new Error(`PedidosYa create shipping failed: ${res.status} ${text}`);
  }
  const data = (await res.json()) as PedidosYaShippingResponse;
  if (!data.shippingId) throw new Error("PedidosYa create response missing 'shippingId'");

  return {
    trackingNumber: data.shippingId,
    orderId: data.shippingId,
    confirmationCode: data.confirmationCode,
    labelUrl: null, // v3 exposes shareLocationUrl, not a PDF label
    shareLocationUrl: data.shareLocationUrl ?? null,
    estimatedDelivery: data.route?.deliveryTimeTo ?? null,
    service: data.route?.deliveryMode ?? "EXPRESS",
  };
}

// ── Tracking ────────────────────────────────────────────────────────────────

/** Resolve the current status + live position for a shipping order.
 *  Combines GET /v3/shippings/{id} (status enum) with the /tracking position. */
export async function fetchPedidosYaTrack(
  token: string,
  shippingId: string,
): Promise<PedidosYaTrackResult> {
  const id = encodeURIComponent(shippingId);
  const statusRes = await fetch(`${PYA_BASE_URL}/v3/shippings/${id}`, {
    method: "GET",
    headers: { Authorization: token },
  });
  if (!statusRes.ok) {
    throw new Error(`PedidosYa track failed: ${statusRes.status} ${statusRes.statusText}`);
  }
  const status = (await statusRes.json()) as PedidosYaShippingResponse;

  // Live position is best-effort — never fail tracking if the position read errors.
  let position: PedidosYaTrackingResponse | null = null;
  try {
    const posRes = await fetch(`${PYA_BASE_URL}/v3/shippings/${id}/tracking`, {
      method: "GET",
      headers: { Authorization: token },
    });
    if (posRes.ok) position = (await posRes.json()) as PedidosYaTrackingResponse;
  } catch {
    position = null;
  }

  const events: PedidosYaTrackResult["events"] = [];
  if (position?.estimatedDropOffTime) {
    events.push({
      timestamp: position.estimatedDropOffTime,
      description: `Entrega estimada${position.deliveryName ? ` — repartidor ${position.deliveryName}` : ""}`,
      location: position.deliveryTransport,
    });
  }
  return {
    trackingNumber: shippingId,
    provider: "pedidosya",
    status: status.status ?? "UNKNOWN",
    events,
  };
}
