"use client";

import { useMemo } from "react";
import type { DashboardState } from "./types";
import type { BusinessDataContextValue } from "./BusinessDataContext";

export function useBusinessDataValue(state: DashboardState): BusinessDataContextValue {
  return useMemo<BusinessDataContextValue>(
    () => ({
      locale: state.locale,
      business: state.business,
      products: state.products,
      clients: state.clients,
      clientDrafts: state.clientDrafts,
      manufacturers: state.manufacturers,
      supplierDrafts: state.supplierDrafts,
      sales: state.sales,
      cashMovements: state.cashMovements,
      invoices: state.invoices,
      lastUpdated: state.lastUpdated,
      notifications: state.notifications,
      settingsForm: state.settingsForm,
      settingsSaving: state.settingsSaving,
      settingsError: state.settingsError,
      settingsNotice: state.settingsNotice,
      loadingPage: state.loadingPage,
      pageError: state.pageError,
      currentCash: state.currentCash,
      totalIncome: state.totalIncome,
      totalExpense: state.totalExpense,
      inventoryChanges: state.inventoryChanges,
      selectedInvoice: state.selectedInvoice,
      selectedInvoiceBusiness: state.selectedInvoiceBusiness,
      selectedInvoiceCustomer: state.selectedInvoiceCustomer,
      selectedInvoiceSale: state.selectedInvoiceSale,
      latestPurchaseRequestPayload: state.latestPurchaseRequestPayload,
      newClient: state.newClient,
      newClientSheetRequestId: state.newClientSheetRequestId,
      clientSaving: state.clientSaving,
      clientError: state.clientError,
      clientNotice: state.clientNotice,
      newSupplier: state.newSupplier,
      supplierSaving: state.supplierSaving,
      supplierError: state.supplierError,
      supplierNotice: state.supplierNotice,
      activeInvoiceId: state.activeInvoiceId,
      invoiceStatusNotice: state.invoiceStatusNotice,
      downloadingInvoiceId: state.downloadingInvoiceId,
      downloadingPurchaseRequestId: state.downloadingPurchaseRequestId,
      savedProductId: state.savedProductId,
      savedClientId: state.savedClientId,
      savedSupplierId: state.savedSupplierId,
    }),
    [
      state.locale,
      state.business,
      state.products,
      state.clients,
      state.clientDrafts,
      state.manufacturers,
      state.supplierDrafts,
      state.sales,
      state.cashMovements,
      state.invoices,
      state.lastUpdated,
      state.notifications,
      state.settingsForm,
      state.settingsSaving,
      state.settingsError,
      state.settingsNotice,
      state.loadingPage,
      state.pageError,
      state.currentCash,
      state.totalIncome,
      state.totalExpense,
      state.inventoryChanges,
      state.selectedInvoice,
      state.selectedInvoiceBusiness,
      state.selectedInvoiceCustomer,
      state.selectedInvoiceSale,
      state.latestPurchaseRequestPayload,
      state.newClient,
      state.newClientSheetRequestId,
      state.clientSaving,
      state.clientError,
      state.clientNotice,
      state.newSupplier,
      state.supplierSaving,
      state.supplierError,
      state.supplierNotice,
      state.activeInvoiceId,
      state.invoiceStatusNotice,
      state.downloadingInvoiceId,
      state.downloadingPurchaseRequestId,
      state.savedProductId,
      state.savedClientId,
      state.savedSupplierId,
    ],
  );
}
